# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
    nuget-feed-version: V3

updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    targetFramework: net10.0
    target-branch: main
    reviewers:
      - "trejjam" # Jan Trejbal
    commit-message:
      prefix: "chore"
      include: "scope" # Adds the dependency name to the commit message
    registries:
      - nuget
    groups:
      microsoft:
        patterns:
          - Microsoft.*
          - System.*
      xunit:
        patterns:
          - xunit
          - xunit.*
