name: PR CI Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - name: Setup .Net 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Setup .Net 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v2
      - name: Retore
        run: dotnet restore --nologo
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Setup .Net 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Tool restore with .Net
        run: dotnet tool restore
      - name: Retore
        run: dotnet restore --nologo src
      - name: .Net Format
        run: dotnet format --no-restore --verify-no-changes -v diag src
